!!com.compuware.ispw.cli.model.IspwRoot
ispwApplication:
  application: GIT1
  host: cw09
  pathMappings:
  - path: \ASM
    types:
    - fileExtension: asm
      ispwType: ASM
  - path: \C
    types:
    - fileExtension: c
      ispwType: C
  - path: \CLST
    types:
    - fileExtension: clst
      ispwType: CLST
  - path: \COB
    types:
    - fileExtension: cbl
      ims: 'No'
      ispwType: COB
      progType: 'Yes'
      sql: 'No'
  - path: \COPY
    types:
    - fileExtension: cpy
      ispwType: COPY
  - path: \JCL
    types:
    - fileExtension: jcl
      ispwType: JCL
  - path: \JOB
    types:
    - fileExtension: jcl
      ispwType: JOB
  - path: \LST
    types:
    - fileExtension: srx
      ispwType: LST
  - path: \PLI
    types:
    - fileExtension: pli
      ispwType: PLI
  port: 47623
  runtimeConfig: tpzp
  stream: PLAY
